### ISSUE TITLE
Add new repositories under development

### ISSUE THREAD

**Issue by brynwhyman** [creative-commoners/dashboard#4]
Add to `config.yml`:

- [x] ~firesphere/silverstripe-boostrapmfa~
- [x] ~silverstripe/silvertripe-login-fomrs~
- [x] silverstripe/silverstripe-u2f-authenticator
- [x] elliot-sawyer/totp-authenticator
- [x] silverstripe/silverstripe-ckan-registry
- [x] silverstripe/silverstripe-mfa

Note this will probably require some CSS to have all repos presented on one screen without scrolling

**Comment by robbieaverill** [comment]
Let's add silverstripe/silverstripe-u2f-authenticator when it's been started. I've added everything but the ones on travis-ci.com aren't showing up. Will need to add config to tell the dashboard to use that API instead for some repos.

**Comment by robbieaverill** [comment]
I've replaced the Travis Ruby library with Faraday HTTP calls - this should fix both the fact that travis-ci.com repos don't work, and that the cron-initiated builds (e.g. kitchen-sink) continue to report as broken. I've just re-deployed to the dashboard and it looks good, so closing
