### ISSUE TITLE
Add visual indication somewhere of code coverage levels per-repo

### ISSUE THREAD

**Issue by robbieaverill** [creative-commoners/dashboard#7]
It'd be cool to show somehow what the code coverage level is like for each repository, example (arbitrary):

![image](https://user-images.githubusercontent.com/5170590/57597255-cadacf00-75a2-11e9-8177-b93bb74c250e.png)

I think codecov.io will provide its definition of what constitutes good coverage levels etc, since that is configurable in its system, and powers its own readme badge colours.

I think the primary focus of the colours should still be indicate the build status, but maybe something like a variable border colour could be used to add some extra context.

cc @sachajudd for thoughts

**Comment by sachajudd** [comment]
Just discussed with @robbieaverill offline. Will have a review once you've set it up to see visually what it looks like before making any decisions 🙂

**Comment by robbieaverill** [comment]
To be fair, this could just be a separate dashboard screen

**Comment by ScopeyNZ** [comment]
Do you think we could have some accessible design that shows a line graph behind the label?

**Comment by robbieaverill** [comment]
I'm gonna start this with a bar graph, e.g. https://github.com/jorgemorgado/dashing-barchart. Maybe try and combine this into the other one and show both

**Comment by robbieaverill** [comment]
Here's a WIP example of what I was working on recently. I'd also like to put gauges in one of the top corners indicating the number of open PRs and open bugs - presume I can get this data from the data warehouse.

![image](https://user-images.githubusercontent.com/5170590/61616959-13310000-ac6a-11e9-842b-26317e1ca070.png)

* Bar graph doesn't contain all repos in this screenshot
* I've changed the Travis widget to only show repos that aren't completely green
* It now shows how many are "healthy" (hidden)

**Comment by robbieaverill** [comment]
I've done this and deployed it to the Pi. I'm not sure how it will look on the TV, so the team will need to let me know =)

![image](https://user-images.githubusercontent.com/5170590/61800459-55566f00-ae2d-11e9-943d-6c04f1c6949d.png)
